// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDFeHok7PeYkzEBsZnRfw4YjP4h-RbjI',
    appId: '1:352707627532:android:8b1fbafd7fd2363a99fc29',
    messagingSenderId: '352707627532',
    projectId: 'gestorrestaurante-12090',
    databaseURL: 'https://gestorrestaurante-12090.firebaseio.com',
    storageBucket: 'gestorrestaurante-12090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjS7hKRCQGlrAbhMGYNIIc6IKLXhkgMUQ',
    appId: '1:352707627532:ios:84eee15a9221b0ea99fc29',
    messagingSenderId: '352707627532',
    projectId: 'gestorrestaurante-12090',
    databaseURL: 'https://gestorrestaurante-12090.firebaseio.com',
    storageBucket: 'gestorrestaurante-12090.appspot.com',
    iosClientId: '352707627532-817cod4os84pds749ck64k4bccvk9bpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.app-comics',
  );
}
